'''


Created on November 2012

@author: pbradley
'''
import time
#import TestHelper
from Actions import Actions
import logging

class ADTActions (Actions):
    def __init__(self, VistAconn, scheduling=None, user=None, code=None):
        Actions.__init__(self, VistAconn, scheduling, user, code)

    def signon (self):
        if self.acode is None:
            self.VistA.wait('');
            self.VistA.write('S DUZ=1 D ^XUP')
        else:
            self.VistA.wait('')
            self.VistA.write('D ^ZU')
            self.VistA.wait('ACCESS CODE:')
            self.VistA.write(self.acode)
            self.VistA.wait('VERIFY CODE:')
            self.VistA.write(self.vcode)
            self.VistA.wait('//')
            self.VistA.write('')
            self.VistA.wait('Option:')
            self.VistA.write('ADT MANAGER MENU')
            self.VistA.wait('continue')
            self.VistA.write('')

    def write(self, string):
        self.VistA.write(string)

    def adt_setup(self):
        self.VistA.wait('OPTION NAME:')
        # DEFINE THE WARD
        self.VistA.write('WARD DEFINITION ENTRY')
        self.VistA.wait('NAME:')
        self.VistA.write('TESTWARD1')
        self.VistA.wait('No//')
        self.VistA.write('YES')
        self.VistA.wait('POINTER:')
        self.VistA.write('Clinic3')
        self.VistA.wait('ORDER:')
        self.VistA.write('5')
        self.VistA.wait('TESTWARD1//')
        self.VistA.write('')
        self.VistA.wait('WRISTBAND:')
        self.VistA.write('YES')
        self.VistA.wait('DIVISION:')
        self.VistA.write('VISTA MEDICAL CENTER')
        self.VistA.wait('INSTITUTION:')
        self.VistA.write('VISTA HEALTH CARE')
        self.VistA.wait('6100')
        self.VistA.write('')
        self.VistA.wait('BEDSECTION:')
        self.VistA.write('bedselect')
        self.VistA.wait('SPECIALTY:')
        self.VistA.write('Cardiac Surgery')
        self.VistA.wait('SERVICE:')
        self.VistA.write('S')
        self.VistA.wait('LOCATION:')
        self.VistA.write('north')
        self.VistA.wait('WARD:')
        self.VistA.write('1')
        self.VistA.wait('DATE:')
        self.VistA.write('T')
        self.VistA.wait('No//')
        self.VistA.write('YES')
        self.VistA.wait('BEDS:')
        self.VistA.write('20')
        self.VistA.wait('ILL:')
        self.VistA.write('1')
        self.VistA.wait('SYNONYM:')
        self.VistA.write('')
        self.VistA.wait('5//')
        self.VistA.write('')
        self.VistA.wait('TOTALS:')
        self.VistA.write('')
        self.VistA.wait('NAME:')
        self.VistA.write('')
        self.VistA.wait('VISTA')
        self.VistA.write('D ^XUP')
        # SETUP BEDS
        self.VistA.wait('OPTION NAME:')
        self.VistA.write('ADT SYSTEM')
        self.VistA.wait('Option:')
        self.VistA.write('ADD')
        self.VistA.wait('NAME:')
        self.VistA.write('1-A')
        self.VistA.wait('No//')
        self.VistA.write('yes')
        self.VistA.wait('1-A//')
        self.VistA.write('')
        self.VistA.wait('DESCRIPTION:')
        self.VistA.write('bed1')
        self.VistA.wait('No//')
        self.VistA.write('yes')
        self.VistA.wait('ASSIGN:')
        self.VistA.write('TESTWARD1')
        self.VistA.wait('No//')
        self.VistA.write('yes')
        self.VistA.wait('ASSIGN:')
        self.VistA.write('')
        self.VistA.wait('NAME:')
        self.VistA.write('1-B')
        self.VistA.wait('No//')
        self.VistA.write('yes')
        self.VistA.wait('1-B//')
        self.VistA.write('')
        self.VistA.wait('DESCRIPTION:')
        self.VistA.write('bed2')
        self.VistA.wait('No//')
        self.VistA.write('yes')
        self.VistA.wait('ASSIGN:')
        self.VistA.write('TESTWARD1')
        self.VistA.wait('No//')
        self.VistA.write('yes')
        self.VistA.wait('ASSIGN:')
        self.VistA.write('')
        self.VistA.wait('NAME:')
        self.VistA.write('2-A')
        self.VistA.wait('No//')
        self.VistA.write('yes')
        self.VistA.wait('2-A//')
        self.VistA.write('')
        self.VistA.wait('DESCRIPTION:')
        self.VistA.write('bed3')
        self.VistA.wait('No//')
        self.VistA.write('yes')
        self.VistA.wait('ASSIGN:')
        self.VistA.write('TESTWARD1')
        self.VistA.wait('No//')
        self.VistA.write('yes')
        self.VistA.wait('ASSIGN:')
        self.VistA.write('')
        self.VistA.wait('NAME:')
        self.VistA.write('2-B')
        self.VistA.wait('No//')
        self.VistA.write('yes')
        self.VistA.wait('2-B//')
        self.VistA.write('')
        self.VistA.wait('DESCRIPTION:')
        self.VistA.write('bed4')
        self.VistA.wait('No//')
        self.VistA.write('yes')
        self.VistA.wait('ASSIGN:')
        self.VistA.write('TESTWARD1')
        self.VistA.wait('No//')
        self.VistA.write('yes')
        self.VistA.wait('ASSIGN:')
        self.VistA.write('')
        self.VistA.wait('NAME:')
        self.VistA.write('')
        self.VistA.wait('Option:')
        self.VistA.write('')
        self.VistA.wait('YES//')
        self.VistA.write('')
        self.VistA.wait('VISTA>')
        self.VistA.write('D ^XUP')
        # ADD ENTRY TO FILE 395
        self.VistA.wait('NAME:')
        self.VistA.write('ZZFILEMAN')
        self.VistA.wait('FileMan')
        self.VistA.write('395')
        self.VistA.wait('OPTION:')
        self.VistA.write('1')
        self.VistA.wait('//')
        self.VistA.write('395')
        self.VistA.wait('ALL//')
        self.VistA.write('')
        self.VistA.wait('ONE:')
        self.VistA.write('1')
        self.VistA.wait('No//')
        self.VistA.write('yes')
        self.VistA.wait('SCREENS?:')
        self.VistA.write('NO')
        self.VistA.wait('DAY:')
        self.VistA.write('')
        self.VistA.wait('NET-WORKDAY:')
        self.VistA.write('')
        self.VistA.wait('OFFSET:')
        self.VistA.write('')
        self.VistA.wait('ENABLED:')
        self.VistA.write('')
        self.VistA.wait('ENABLED:')
        self.VistA.write('')
        self.VistA.wait('INTENSITY?:')
        self.VistA.write('')
        self.VistA.wait('ERRORS:')
        self.VistA.write('')
        self.VistA.wait('LIMIT:')
        self.VistA.write('')
        self.VistA.wait('COUNTER:')
        self.VistA.write('')
        self.VistA.wait('MESSAGES:')
        self.VistA.write('')
        self.VistA.wait('INTERFACE:')
        self.VistA.write('')
        self.VistA.wait('INTERFACE:')
        self.VistA.write('0')
        self.VistA.wait('Difference:')
        self.VistA.write('')
        self.VistA.wait('DIVISION:')
        self.VistA.write('YES')
        self.VistA.wait('GROUP:')
        self.VistA.write('')
        self.VistA.wait('ADDRESS:')
        self.VistA.write('^')
        self.VistA.wait('ONE:')
        self.VistA.write('')
        self.VistA.wait('OPTION:')
        self.VistA.write('1')
        # ADD ENTRY TO MAS PARAMETER FILE 43
        self.VistA.wait('//')
        self.VistA.write('43')
        self.VistA.wait('ALL//')
        self.VistA.write('')
        self.VistA.wait('ONE:')
        self.VistA.write('1')
        self.VistA.wait('ONE:')
        self.VistA.write('1')
        self.VistA.wait('WARD:')
        self.VistA.write('')
        self.VistA.wait('TIMEOUT:')
        self.VistA.write('30')
        self.VistA.wait('CORR:')
        self.VistA.write('30')
        self.VistA.wait('DISPOSITION:')
        self.VistA.write('30')
        self.VistA.wait('10/10:')
        self.VistA.write('')
        self.VistA.wait('10-10:')
        self.VistA.write('')
        self.VistA.wait('PRINTER:')
        self.VistA.write('')
        self.VistA.wait('MESSAGES?:')
        self.VistA.write('')
        self.VistA.wait('MESSAGES?:')
        self.VistA.write('')
        self.VistA.wait('G&L:')
        self.VistA.write('T')
        self.VistA.wait('CENTER?:')
        self.VistA.write('NO')
        self.VistA.wait('NAME:')
        self.VistA.write('VISTA')
        self.VistA.wait('AFFILIATED:')
        self.VistA.write('0')
        self.VistA.wait('SITE:')
        self.VistA.write('')
        self.VistA.wait('WARDS?:')
        self.VistA.write('')
        self.VistA.wait('WARDS?:')
        self.VistA.write('')
        self.VistA.wait('INQUIRY?:')
        self.VistA.write('')
        self.VistA.wait('ON-LINE:')
        self.VistA.write('')
        self.VistA.wait('PRINTER:')
        self.VistA.write('')
        self.VistA.wait('PRINTER:')
        self.VistA.write('')
        self.VistA.wait('DEFAULT:')
        self.VistA.write('')
        self.VistA.wait('DEFAULT:')
        self.VistA.write('0')
        self.VistA.wait('SENSITIVITY:')
        self.VistA.write('30')
        self.VistA.wait('SCREEN:')
        self.VistA.write('')
        self.VistA.wait('SCREEN:')
        self.VistA.write('0')
        self.VistA.wait('ON?:')
        self.VistA.write('')
        self.VistA.wait('INQUIRY?:')
        self.VistA.write('')
        self.VistA.wait('REGISTRATION:')
        self.VistA.write('YES')
        self.VistA.wait('SUMMARY?:')
        self.VistA.write('')
        self.VistA.wait('SUMMARY:')
        self.VistA.write('')
        self.VistA.wait('TYPE?:')
        self.VistA.write('')
        self.VistA.wait('PROFILE:')
        self.VistA.write('')
        self.VistA.wait('MEDICAID:')
        self.VistA.write('')
        self.VistA.wait('REG.:')
        self.VistA.write('')
        self.VistA.wait('PRINTER:')
        self.VistA.write('')
        self.VistA.wait('STARTED:')
        self.VistA.write('')
        self.VistA.wait('STARTED:')
        self.VistA.write('')
        self.VistA.wait('TO:')
        self.VistA.write('')
        self.VistA.wait('ZTSK(RECALC):')
        self.VistA.write('^')
        self.VistA.wait('ONE:')
        self.VistA.write('')
        self.VistA.wait('OPTION:')
        self.VistA.write('')
        self.VistA.wait('VISTA>')
        self.VistA.write('')


    def admit_a_patient(self, ssn, bed):
        self.VistA.wait('OPTION NAME:')
        self.VistA.write('BED CONTROL MENU')
        self.VistA.wait('Option:')
        self.VistA.write('admit a patient')
        self.VistA.wait('PATIENT:')
        self.VistA.write(ssn)
        self.VistA.wait('CONTINUE//')
        self.VistA.write('C')
        self.VistA.wait('NOW//')
        self.VistA.write('NOW')
        self.VistA.wait('//')
        self.VistA.write('YES')
        self.VistA.wait('DIRECTORY?:')
        self.VistA.write('NO')
        self.VistA.wait('REGULATION:')
        self.VistA.write('OBSERVATION')
        self.VistA.wait('CONDITION?:')
        self.VistA.write('NO')
        self.VistA.wait('ADMISSION:')
        self.VistA.write('DIRECT')
        self.VistA.wait('[SHORT]:')
        self.VistA.write('TESTCONDITION')
        self.VistA.wait('LOCATION:')
        self.VistA.write('TESTWARD1')
        self.VistA.wait('ROOM-BED:')
        self.VistA.write(bed)
        self.VistA.wait('SPECIALTY:')
        self.VistA.write('MEDICAL OBSERVATION')
        self.VistA.wait('PHYSICIAN:')
        self.VistA.write('Alexander')
        self.VistA.wait('PHYSICIAN:')
        self.VistA.write('Smith')
        self.VistA.wait('Option:')
        self.VistA.write('')
        self.VistA.wait('ADMISSION:')
        self.VistA.write('VA MEDICAL CENTER')
        self.VistA.wait('ILL//')
        self.VistA.write('')
        self.VistA.wait('PATIENT:')
        self.VistA.write('')
        self.VistA.wait('Option:')
        self.VistA.write('')

    def roster_list(self, vlist):
        self.VistA.wait('OPTION NAME:')
        self.VistA.write('ADT MANAGER MENU')
        self.VistA.wait('continue')
        self.VistA.write('')
        self.VistA.wait('Option:')
        self.VistA.write('ADT OUTPUTS MENU')
        self.VistA.wait('Option:')
        self.VistA.write('inpatient/lodger report menu')
        self.VistA.wait('Option:')
        self.VistA.write('inpatient listing')
        self.VistA.wait('WARD//')
        self.VistA.write('ward')
        self.VistA.wait('FIRST//')
        self.VistA.write('')
        self.VistA.wait('LAST//')
        self.VistA.write('')
        self.VistA.wait('YES//')
        self.VistA.write('')
        self.VistA.wait('YES//')
        self.VistA.write('')
        self.VistA.wait('HOME//')
        self.VistA.write('')
        self.VistA.wait('Continue')
        self.VistA.write('')
        for vitem in vlist:
            self.VistA.wait(vitem)
        self.VistA.write('')
        self.VistA.wait('Option:')
        self.VistA.write('')

    def discharge_patient(self, ssn):
        self.VistA.wait('OPTION NAME:')
        self.VistA.write('ADT MANAGER MENU')
        self.VistA.wait('continue')
        self.VistA.write('')
        self.VistA.wait('Option:')
        self.VistA.write('bed control menu')
        self.VistA.wait('Option:')
        self.VistA.write('discharge a patient')
        self.VistA.wait('PATIENT:')
        self.VistA.write(ssn)
        self.VistA.wait('CONTINUE//')
        self.VistA.write('C')
        self.VistA.wait('NOW//')
        self.VistA.write('')
        self.VistA.wait('DISCHARGE:')
        self.VistA.write('regular')
        self.VistA.wait('NO//')
        self.VistA.write('NO')
        self.VistA.wait('PATIENT:')
        self.VistA.write('')
        self.VistA.wait('Option:')
        self.VistA.write('')

    def scheduled_admit_list(self, vlist):
        self.VistA.wait('OPTION NAME:')
        self.VistA.write('ADT MANAGER MENU')
        self.VistA.wait('continue')
        self.VistA.write('')
        self.VistA.wait('Option:')
        self.VistA.write('ADT MANAGER MENU')
        self.VistA.wait('continue')
        self.VistA.write('')
        self.VistA.wait('Option:')
        self.VistA.write('adt outputs menu')
        self.VistA.wait('Option:')
        self.VistA.write('scheduled admission list')
        self.VistA.wait('Option:')
        self.VistA.write('scheduled admissions list')
        self.VistA.wait('//')
        self.VistA.write('T')
        self.VistA.wait('//')
        self.VistA.write('T+5')
        self.VistA.wait('BOTH//')
        self.VistA.write('BOTH')
        self.VistA.wait('columns')
        self.VistA.write('')
        for vitem in vlist:
            self.VistA.wait(vitem)
        self.VistA.write('')
        self.VistA.wait('Option:')
        self.VistA.write('')

    def transfer_patient(self,ssn):
        self.VistA.wait('OPTION NAME:')
        self.VistA.write('ADT MANAGER MENU')
        self.VistA.wait('continue')
        self.VistA.write('')
        self.VistA.wait('Option:')
        self.VistA.write('adt manager menu')
        self.VistA.wait('continue')
        self.VistA.write('')
        self.VistA.wait('Option:')
        self.VistA.write('bed control menu')
        self.VistA.wait('Option:')
        self.VistA.write('transfer a patient')
        self.VistA.wait('PATIENT:')
        self.VistA.write(ssn)
        self.VistA.wait('CONTINUE//')
        self.VistA.write('C')
        self.VistA.wait('NOW//')
        self.VistA.write('now')
        self.VistA.wait('Yes//')
        self.VistA.write('yes')
        self.VistA.wait('TRANSFER:')
        self.VistA.write('??')
        self.VistA.wait('TRANSFER:')
        self.VistA.write('TO AUTHORIZED ABSENCE')
        self.VistA.wait('ACTIVE')
        self.VistA.write('1')
        self.VistA.wait('DATE:')
        self.VistA.write('T+5')
        self.VistA.wait('ILL//')
        self.VistA.write('')
        self.VistA.wait('PATIENT:')
        self.VistA.write('')
        self.VistA.wait('Option:')
        self.VistA.write('')

    def schedule_admission(self, ssn):
        self.VistA.wait('NAME:')
        self.VistA.write('adt manager menu')
        self.VistA.wait('continue')
        self.VistA.write('')
        self.VistA.wait('Option:')
        self.VistA.write('bed control menu')
        self.VistA.wait('option')
        self.VistA.write('schedule an admission')
        self.VistA.wait('patient:')
        self.VistA.write(ssn)
        self.VistA.wait('No//')
        self.VistA.write('yes')
        self.VistA.wait('DATE/TIME:')
        self.VistA.write('T+1@10am')
        self.VistA.wait('//')
        self.VistA.write('')
        self.VistA.wait('SPECIALTY:')
        self.VistA.write('ward')
        self.VistA.wait('WARD:')
        self.VistA.write('testward1')
        self.VistA.wait('')
        self.VistA.write('')
        self.VistA.wait('EXPECTED:')
        self.VistA.write('5')
        self.VistA.wait('DIAGNOSIS:')
        self.VistA.write('medical observation')
        self.VistA.wait('PROVIDER:')
        self.VistA.write('alexander')
        self.VistA.wait('SURGERY:')
        self.VistA.write('smith')
        self.VistA.wait('NO')
        self.VistA.write('n')
        self.VistA.wait('STATUS:')
        self.VistA.write('')
        self.VistA.wait('No//')
        self.VistA.write('')
        self.VistA.wait('patient:')
        self.VistA.write('')
        self.VistA.wait('Option:')
        self.VistA.write('')

    def cancel_scheduled_admission(self, ssn):
        self.VistA.wait('OPTION NAME:')
        self.VistA.write('adt manager menu')
        self.VistA.wait('continue')
        self.VistA.write('')
        self.VistA.wait('Option:')
        self.VistA.write('bed control menu')
        self.VistA.wait('Option:')
        self.VistA.write('cancel a scheduled admission')
        self.VistA.wait('patient:')
        self.VistA.write(ssn)
        self.VistA.wait('Yes//')
        self.VistA.write('yes')
        self.VistA.wait('CANCELLED:')
        self.VistA.write('NOW')
        self.VistA.wait('CANCELLED:')
        self.VistA.write('test')
        self.VistA.wait('BEDS')
        self.VistA.write('other')
        self.VistA.wait('NOTIFIED:')
        self.VistA.write('YES')
        self.VistA.wait('patient:')
        self.VistA.write('')
        self.VistA.wait('Option:')
        self.VistA.write('')
